name: build mbtiles

on:
  workflow_dispatch:
  schedule:
    - cron: "1 2 * * *"

jobs:
  build-mbtiles:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2

      - name: Build mbtiles
        run: bash scripts/build-mbtiles.sh

      - name: Commit built pois
        run: |-
          git config user.name "ParkBot"
          git config user.email "actions@users.noreply.github.com"
          git add pages/*
          git commit -m "`date +'%Y-%m-%d'` updated park boundaries" || exit 0
          git push
