name: regenerate tiles

on:
  workflow_dispatch:

jobs:
  regenerate-tiles:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Regenerate tiles
        run: yarn regenerate

      - name: Commit built tiles
        run: |-
          git config user.name "ParkBot"
          git config user.email "actions@users.noreply.github.com"
          git add pages/*
          git commit -m "`date +'%Y-%m-%d'` updated park boundaries" || exit 0
          git push
